name: Update yarn.lock

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_lockfile:
    name: Update yarn.lock
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update yarn.lock
        run: yarn install

      - name: Check if lockfile changed
        id: lockfile-check
        run: |
          if git diff --quiet yarn.lock; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push lockfile
        if: steps.lockfile-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add yarn.lock
          git commit -m "chore: update yarn.lock"
          git push

      - name: No changes needed
        if: steps.lockfile-check.outputs.changed == 'false'
        run: echo "yarn.lock is already up to date"
